"""Update models for multi-provider payment system

Revision ID: bf25aa0ffc73
Revises: bbd67ea57409
Create Date: 2026-01-20 18:45:40.315266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf25aa0ffc73'
down_revision: Union[str, None] = 'bbd67ea57409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('signature', sa.String(length=500), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_event_type'), 'webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_events_processed'), 'webhook_events', ['processed'], unique=False)
    op.create_index(op.f('ix_webhook_events_provider'), 'webhook_events', ['provider'], unique=False)
    op.create_index(op.f('ix_webhook_events_provider_event_id'), 'webhook_events', ['provider_event_id'], unique=True)
    op.create_index(op.f('ix_webhook_events_received_at'), 'webhook_events', ['received_at'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('refund_reason', sa.Text(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_provider'), 'payments', ['provider'], unique=False)
    op.create_index(op.f('ix_payments_provider_payment_id'), 'payments', ['provider_payment_id'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_subscription_id'), 'payments', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.drop_index(op.f('ix_billing_events_event_type'), table_name='billing_events')
    op.drop_index(op.f('ix_billing_events_user_id'), table_name='billing_events')
    op.drop_table('billing_events')
    op.drop_index(op.f('ix_subscription_history_subscription_id'), table_name='subscription_history')
    op.drop_table('subscription_history')
    op.create_index(op.f('ix_api_keys_revoked'), 'api_keys', ['revoked'], unique=False)
    op.drop_constraint(op.f('api_keys_user_id_fkey'), 'api_keys', type_='foreignkey')
    op.create_foreign_key(None, 'api_keys', 'profiles', ['user_id'], ['id'], ondelete='CASCADE')
    
    # Add nullable columns first for plans
    op.add_column('plans', sa.Column('pricing', sa.JSON(), nullable=True))
    op.add_column('plans', sa.Column('provider_ids', sa.JSON(), nullable=True))
    op.add_column('plans', sa.Column('is_active', sa.Boolean(), nullable=True))
    
    # Populate new columns with default values
    op.execute("UPDATE plans SET pricing = '{}' WHERE pricing IS NULL")
    op.execute("UPDATE plans SET provider_ids = '{}' WHERE provider_ids IS NULL")
    op.execute("UPDATE plans SET is_active = active WHERE is_active IS NULL")
    
    # Make columns non-nullable
    op.alter_column('plans', 'pricing', nullable=False)
    op.alter_column('plans', 'is_active', nullable=False)
    
    op.create_index(op.f('ix_plans_is_active'), 'plans', ['is_active'], unique=False)
    op.drop_column('plans', 'lemon_squeezy_product_id')
    op.drop_column('plans', 'price_annually')
    op.drop_column('plans', 'active')
    op.drop_column('plans', 'price_monthly')
    op.add_column('profiles', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=False)
    
    # Add nullable columns first for subscriptions
    op.add_column('subscriptions', sa.Column('provider', sa.String(length=20), nullable=True))
    op.add_column('subscriptions', sa.Column('provider_subscription_id', sa.String(length=255), nullable=True))
    op.add_column('subscriptions', sa.Column('current_period_start', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('current_period_end', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('cancel_at_period_end', sa.Boolean(), nullable=True))
    op.add_column('subscriptions', sa.Column('trial_end', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('event_log', sa.JSON(), nullable=True))
    
    # Populate new columns with default values
    op.execute("UPDATE subscriptions SET provider = 'dodo' WHERE provider IS NULL")
    op.execute("UPDATE subscriptions SET provider_subscription_id = COALESCE(lemon_squeezy_subscription_id, id::text) WHERE provider_subscription_id IS NULL")
    op.execute("UPDATE subscriptions SET current_period_start = start_date WHERE current_period_start IS NULL")
    op.execute("UPDATE subscriptions SET current_period_end = COALESCE(end_date, start_date + interval '30 days') WHERE current_period_end IS NULL")
    op.execute("UPDATE subscriptions SET cancel_at_period_end = false WHERE cancel_at_period_end IS NULL")
    op.execute("UPDATE subscriptions SET event_log = '[]' WHERE event_log IS NULL")
    
    # Make columns non-nullable
    op.alter_column('subscriptions', 'provider', nullable=False)
    op.alter_column('subscriptions', 'provider_subscription_id', nullable=False)
    op.alter_column('subscriptions', 'current_period_start', nullable=False)
    op.alter_column('subscriptions', 'current_period_end', nullable=False)
    op.alter_column('subscriptions', 'cancel_at_period_end', nullable=False)
    
    op.drop_index(op.f('ix_subscriptions_lemon_squeezy_subscription_id'), table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_provider'), 'subscriptions', ['provider'], unique=False)
    op.create_index(op.f('ix_subscriptions_provider_subscription_id'), 'subscriptions', ['provider_subscription_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.drop_constraint(op.f('subscriptions_user_id_fkey'), 'subscriptions', type_='foreignkey')
    op.drop_constraint(op.f('subscriptions_plan_id_fkey'), 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'profiles', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'subscriptions', 'plans', ['plan_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('subscriptions', 'price_id')
    op.drop_column('subscriptions', 'start_date')
    op.drop_column('subscriptions', 'end_date')
    op.drop_column('subscriptions', 'auto_renew')
    op.drop_column('subscriptions', 'lemon_squeezy_subscription_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('lemon_squeezy_subscription_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('auto_renew', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('price_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('subscriptions_plan_id_fkey'), 'subscriptions', 'plans', ['plan_id'], ['id'])
    op.create_foreign_key(op.f('subscriptions_user_id_fkey'), 'subscriptions', 'profiles', ['user_id'], ['id'])
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_provider_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_provider'), table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_lemon_squeezy_subscription_id'), 'subscriptions', ['lemon_squeezy_subscription_id'], unique=True)
    op.drop_column('subscriptions', 'event_log')
    op.drop_column('subscriptions', 'trial_end')
    op.drop_column('subscriptions', 'cancel_at_period_end')
    op.drop_column('subscriptions', 'current_period_end')
    op.drop_column('subscriptions', 'current_period_start')
    op.drop_column('subscriptions', 'provider_subscription_id')
    op.drop_column('subscriptions', 'provider')
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.drop_column('profiles', 'email')
    op.add_column('plans', sa.Column('price_monthly', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('plans', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('plans', sa.Column('price_annually', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('plans', sa.Column('lemon_squeezy_product_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_plans_is_active'), table_name='plans')
    op.drop_column('plans', 'is_active')
    op.drop_column('plans', 'provider_ids')
    op.drop_column('plans', 'pricing')
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.create_foreign_key(op.f('api_keys_user_id_fkey'), 'api_keys', 'profiles', ['user_id'], ['id'])
    op.drop_index(op.f('ix_api_keys_revoked'), table_name='api_keys')
    op.create_table('subscription_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subscription_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('event_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('event_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('subscription_history_subscription_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('subscription_history_pkey'))
    )
    op.create_index(op.f('ix_subscription_history_subscription_id'), 'subscription_history', ['subscription_id'], unique=False)
    op.create_table('billing_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('billing_events_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('billing_events_pkey'))
    )
    op.create_index(op.f('ix_billing_events_user_id'), 'billing_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_billing_events_event_type'), 'billing_events', ['event_type'], unique=False)
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_subscription_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_webhook_events_received_at'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_provider_event_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_provider'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_processed'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='webhook_events')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
