"""add generation_jobs table

Revision ID: b02b3252a084
Revises: a254f8dc2f95
Create Date: 2026-01-14 10:36:52.610175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b02b3252a084'
down_revision: Union[str, None] = 'a254f8dc2f95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('aspect_ratio', sa.String(length=10), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('video_template_id', sa.Integer(), nullable=True),
    sa.Column('audio_file_path', sa.String(), nullable=True),
    sa.Column('product_image_path', sa.String(), nullable=True),
    sa.Column('output_video_path', sa.String(), nullable=True),
    sa.Column('text_input', sa.Text(), nullable=True),
    sa.Column('voice_id', sa.String(length=100), nullable=True),
    sa.Column('character_description', sa.Text(), nullable=True),
    sa.Column('environment_description', sa.Text(), nullable=True),
    sa.Column('gestures', sa.Text(), nullable=True),
    sa.Column('dialogue', sa.Text(), nullable=True),
    sa.Column('voice_tone', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['video_template_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_jobs_id'), 'generation_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_job_id'), 'generation_jobs', ['job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_jobs_job_id'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_id'), table_name='generation_jobs')
    op.drop_table('generation_jobs')
    # ### end Alembic commands ###
